name: ci
run-name: Tests triggered by ${{ github.event.inputs.origin }}
#run-name: Tests triggered by ${{ github.event.repository.name }}
on:
  workflow_dispatch:
    inputs:
      origin:
        description: 'Service who triggered the tests'
        required: false
        type: string
        default: ${{ github.triggering_actor }}

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Say something
      run: echo 'i am running' 

