name: ci
#run-name: Tests triggered by ${{ github.event.inputs.origin }}
run-name: Tests triggered by ${{ env.ORIGIN }}
on:
  workflow_dispatch:
    inputs:
      origin:
        description: 'Service who triggered the tests'
        required: false
        type: string

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: set actor
      env:
        ORIGIN: ${{ github.event.inputs.origin ||  github.actor}}
      if: env.actor
      run: echo "Flag is available and true"
    
    - name: Say something
      run: echo 'i am running' 

