name: ci 
run-name: Tests triggered by ${{ github.event.inputs.origin }}
on:
  workflow_dispatch:
    inputs:
      origin:
        description: 'Service who triggered the tests'
        required: false
        type: string
      author:
        description: 'Author who triggered the tests'
        required: false
        type: string
        default: 'unknown'
      

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Event Name
      run: echo '{{ github.event_name }}'
      
    - name: Make it fail
      run: pytest

  slack-notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    needs: [my_job]
    if: always() && (needs.my_job.result == 'failure')
    steps:
      - name: Set notification message
        id: set-message
        run: |
          if [[ ${{ needs.my_job.result }} == "failure" ]]
          then
            AUTHOR='${{ github.event.inputs.author }}'          
            MESSAGE=format('{0} by {1}', 'There was an error building the image')
            STATUS="failure"
            ORIGIN='${{ github.event.inputs.origin }}'

          fi
          echo "::set-output name=message::$MESSAGE"
          echo "::set-output name=status::$STATUS"
          echo "::set-output name=author::$AUTHOR"
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '${{ steps.set-message.outputs.message }}'
          SLACK_COLOR: ${{ steps.set-message.outputs.status }}
          SLACK_TITLE: '${{ steps.set-message.outputs.origin }}'
          SLACK_USERNAME: 'Github Actions'
