name: ci
run-name: Tests triggered by ${{ github.event.inputs.origin }}
on:
  workflow_dispatch:
    inputs:
      origin:
        description: 'Service who triggered the tests'
        required: false
        type: string

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    
    - name: Say something
      run: echo 'i am running' 
      
    - name: Make it fail
      run: pytest

