name: ci 
run-name: Tests triggered by ${{ github.event.inputs.origin }}
on:
  workflow_dispatch:
    inputs:
      origin:
        description: 'Service who triggered the tests'
        required: false
        type: string
      author:
        description: 'Author who triggered the tests'
        required: false
        type: string
        default: 'unknown'
       

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Variables
      run: |
            echo '${{ github.event_name }}'
            echo '${{ github.event.inputs.author }}'
            echo '${{ github.event.inputs.origin }}'
            
    - name: Make it fail
      run: pytest

  slack-notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    needs: [my_job]
    if: always() && (needs.my_job.result == 'failure')
    steps:
      - name: Set notification message
        id: set-message
        run: |
          if [[ ${{ needs.my_job.result }} == "failure" ]]
          then
            AUTHOR='${{ github.event.inputs.author }}'
            MESSAGE="There was an error building the image by $AUTHOR"
            STATUS="failure"
            ORIGIN='${{ github.event.inputs.origin }}'
          fi
          echo "origin=$ORIGIN" >> $GITHUB_ENV
          echo "message=$MESSAGE" >> $GITHUB_ENV
          echo "status=$STATUS" >> $GITHUB_ENV
          
          echo ${{ env.origin }}
          echo ${{ env.message }}
          
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '${{ env.message }}'
          SLACK_COLOR: ${{ env.status }}
          SLACK_TITLE: '${{ env.origin }}'
          SLACK_USERNAME: 'Github Actions'
