name: ci


on:
  workflow_dispatch:
    inputs:
      origin:
        description: 'Service who triggered the tests'
        required: false
        type: string      

jobs:
  my_job:
    run-name: Deploy to ${{ github.event.inputs.origin }}
    runs-on: ubuntu-latest
    steps:
    - name: Say something
      run: echo 'i am running' 

