name: ci


on:
  workflow_dispatch

jobs:
  my_job:
    run-name: Deploy to ${{ github.event.inputs.origin }}
    runs-on: ubuntu-latest
    steps:
    - name: Say something
      run: echo 'i am running' 

