name: Print Branch Name

on:
  push:
    branches:
      - main

jobs: 
  print_the_branch_only_on_main:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}    
    steps:
      - name: Print Variables
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
